// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpflpdweqxzzlwyruhjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwZmxwZHdlcXh6emx3eXJ1aGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzY4MzIsImV4cCI6MjA2MDcxMjgzMn0.o40gaeVvdIqgA6MEJDwoiHx50jXyGR1t1Hk6HNfz9RQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);